name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Certificates
      run: apt-get install -y ca-certificates apt-transport-https software-properties-common

    - name: Add repo
      run: add-apt-repository -y ppa:ondrej/php

    - name: Updated environment
      run: apt-get update -y

    - name: Install PHP8
      run: apt-get install php8.0 php8.0-curl php8.0-gd php8.0-xml -y

    - name: Install Composer
      run: apt-get install -y composer

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run composer
      run: composer install

    - name: Run tests
      run: composer run-script test