name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Composer
      uses: php-actions/composer@v5
      with:
        php_version: 8.0
        php_extensions: curl gd xml

    - name: PHPUnit
      uses: php-actions/phpunit@v2
      with:
        bootstrap: vendor/autoload.php
        configuration: phpunit.xml
        args: --testdox --verbose
        php_version: 8.0
        php_extensions: curl gd xml
